# Generated by Django 4.0.3 on 2022-06-09 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sesion', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
