# Generated by Django 4.0.3 on 2022-06-08 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogPlantas', '0008_posteo_imagen_problema_imagen_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='posteo',
            name='tags',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
