# Generated by Django 4.0.3 on 2022-06-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0009_posteo_categoria_posteo_tags_alter_posteo_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenPlanta',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
