# Generated by Django 4.0.3 on 2022-06-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0010_delete_imagenplanta_delete_planta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vivero',
        ),
    ]
