# Generated by Django 4.0.3 on 2022-06-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPlantas', '0011_delete_vivero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Problema',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Posteo',
        ),
    ]
