# Generated by Django 4.0.3 on 2022-06-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categoria_remove_posteo_tags_alter_posteo_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
