# Generated by Django 4.0.5 on 2022-06-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_comentario_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
