# Generated by Django 4.0.3 on 2022-06-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesPlantas')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.planta')),
            ],
        ),
    ]
