# Generated by Django 4.0.3 on 2022-06-11 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_remove_vivero_stockplantas_and_more'),
        ('plantas', '0002_imagenplanta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='viveros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viveros.vivero'),
        ),
    ]
