# Generated by Django 4.0.3 on 2022-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_remove_vivero_stockplantas_and_more'),
        ('plantas', '0004_alter_planta_descripcion_alter_planta_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='viveros',
        ),
        migrations.AddField(
            model_name='planta',
            name='viveros',
            field=models.ManyToManyField(help_text='<br> Mantenga CTRL para seleccionar varios', to='viveros.vivero'),
        ),
    ]
