# Generated by Django 4.0.3 on 2022-06-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_remove_planta_viveros_planta_viveros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='descripcion',
            field=models.TextField(help_text='<br> Descripcion de la planta.', max_length=3000),
        ),
    ]
