# Generated by Django 4.0.5 on 2022-06-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_remove_vivero_stockplantas_and_more'),
        ('problemas', '0005_alter_problema_productos'),
        ('plantas', '0007_alter_planta_peligroscomunes_alter_planta_viveros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='peligrosComunes',
            field=models.ManyToManyField(blank=True, help_text='<br> Mantenga CTRL para seleccionar varios', to='problemas.problema'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='viveros',
            field=models.ManyToManyField(blank=True, help_text='<br> Mantenga CTRL para seleccionar varios', to='viveros.vivero'),
        ),
    ]
