# Generated by Django 4.0.3 on 2022-06-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.IntegerField(help_text='Precio en U$s blue.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesProductos')),
                ('solucionaProblemas', models.CharField(help_text='Problemas que soluciona.', max_length=200)),
                ('puntoDeVenta', models.CharField(help_text='Viveros donde comprarlo.', max_length=200)),
            ],
        ),
    ]
