# Generated by Django 4.0.3 on 2022-06-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_puntodeventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='solucionaProblemas',
        ),
    ]
