# Generated by Django 4.0.3 on 2022-06-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_remove_vivero_stockplantas_and_more'),
        ('productos', '0003_remove_producto_solucionaproblemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='puntoDeVenta',
        ),
        migrations.AddField(
            model_name='producto',
            name='puntoDeVenta',
            field=models.ManyToManyField(help_text='<br> Mantenga CTRL para seleccionar varios', to='viveros.vivero'),
        ),
    ]
