# Generated by Django 4.0.5 on 2022-06-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viveros', '0002_remove_vivero_stockplantas_and_more'),
        ('productos', '0005_alter_producto_puntodeventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='puntoDeVenta',
            field=models.ManyToManyField(blank=True, help_text='<br> Mantenga CTRL para seleccionar varios', to='viveros.vivero'),
        ),
    ]
