# Generated by Django 4.0.3 on 2022-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProblema', models.CharField(max_length=40)),
                ('nombreCientifico', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenesProblemas')),
                ('peligro', models.CharField(help_text='Bajo, Medio o Alto', max_length=10)),
                ('productos', models.CharField(help_text='Productos de ayuda.', max_length=50)),
                ('solucion', models.CharField(help_text='Manera de solucionarlo', max_length=2000)),
            ],
        ),
    ]
