# Generated by Django 4.0.3 on 2022-06-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_puntodeventa_producto_puntodeventa'),
        ('problemas', '0004_alter_problema_peligro_alter_problema_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='productos',
            field=models.ManyToManyField(blank=True, help_text='<br> Mantenga CTRL para seleccionar varios', null=True, to='productos.producto'),
        ),
    ]
