# Generated by Django 4.0.5 on 2022-06-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_puntodeventa'),
        ('problemas', '0005_alter_problema_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problema',
            name='productos',
            field=models.ManyToManyField(blank=True, help_text='<br> Mantenga CTRL para seleccionar varios', to='productos.producto'),
        ),
    ]
